### ISSUE TITLE
3D Convolutional 

### ISSUE THREAD

**Issue by jiangzihanict** [eracah/hur-detect#2]
Hi,
I am very interested in your work and I am reading your NIPS paper. In this paper, you adopted a 3D convolutional model, but I can not find the related code in the TF-keras branch of this repo . So, the 3D version is not opensourced?

Looking forward for your response.
Thanks!

**Comment by eracah** [comment]
Hi Zihan,
Yeah, I guess I never implemented it for the keras version. The theano one is [here:](https://github.com/eracah/hur-detect/blob/master/scripts/build_network.py#L127-L148)

You can probably port the theano code to keras using ```keras.layers.Conv3D```

Hope that helps!

**Comment by jiangzihanict** [comment]
Thanks for your quick reply!

I'll try it!
